- {name: dlink.PortInfoMediumType, oid: .1.3.6.1.4.1.171.11.113.2.1.2.3.2.1.2, values: {1: Cooper, 2: Fiber}}
- {name: dlink.PortInfoLinkStatus, oid: .1.3.6.1.4.1.171.11.113.2.1.2.3.1.1.5, values: {2: Up, 3: Down}}
- {name: dlink.PortInfoNwayStatus, oid: .1.3.6.1.4.1.171.11.113.2.1.2.3.1.1.6, values: {2: Down, 3: 10-Half, 4: 10-Full, 5: 100-Half, 6: 100-Full, 7: 1G-Half, 8: 1G-Full}}
- {name: dlink.PortCtrlPortAdminState, oid: .1.3.6.1.4.1.171.11.113.2.1.2.3.2.1.4, values: {3: Enabled, 2: Disabled}}
- {name: dlink.PortCtrlPortNwayState, oid: .1.3.6.1.4.1.171.11.113.2.1.2.3.2.1.5, values: {2: Auto, 3: 10-Half, 4: 10-Full, 5: 100-Half, 6: 100-Full, 7: 1G-Half, 8: 1G-Full}}
- {name: dlink.PortCtrlAddressLearning, oid: .1.3.6.1.4.1.171.11.113.2.1.2.3.2.1.7, values: {2: Disabled, 3: Enabled}}
- {name: manage.DevCtrlSystemReboot, oid: .1.3.6.1.4.1.171.11.63.6.2.1.2.1,  values: {2: YES, 1: TEST}}
- {name: manage.DevCtrlClearAllStatisticCounter, oid: .1.3.6.1.4.1.171.11.63.6.2.1.2.12} #Syntax = integer
- {name: manage.DevCtrlRmonState, oid: .1.3.6.1.4.1.171.11.63.6.2.1.2.16} #Syntax = integer

#Port diagnostic
- {name: dlink.CableDiagPortIndex, oid: .1.3.6.1.4.1.171.12.58.1.1.1.1}
- {name: dlink.CableDiagPortType, oid: .1.3.6.1.4.1.171.12.58.1.1.1.2, values: {0: FE, 1: GE, 2: Other}}
- {name: dlink.CableDiagLinkStatus, oid: .1.3.6.1.4.1.171.12.58.1.1.1.3, values: {0: Down, 1: Up, 2: Other}}
- {name: dlink.CableDiagPair1Status, oid: .1.3.6.1.4.1.171.12.58.1.1.1.5, values: {0: OK, 1: Open, 2: Short, 3: Open-Short, 4: CrossTalk, 5: Unknown, 6: Count, 7: NoCable, 8: Other}}
- {name: dlink.CableDiagPair2Status, oid: .1.3.6.1.4.1.171.12.58.1.1.1.6, values: {0: OK, 1: Open, 2: Short, 3: Open-Short, 4: CrossTalk, 5: Unknown, 6: Count, 7: NoCable, 8: Other}}
- {name: dlink.CableDiagPair3Status, oid: .1.3.6.1.4.1.171.12.58.1.1.1.4, values: {0: OK, 1: Open, 2: Short, 3: Open-Short, 4: CrossTalk, 5: Unknown, 6: Count, 7: NoCable, 8: Other}}
- {name: dlink.CableDiagPair4Status, oid: .1.3.6.1.4.1.171.12.58.1.1.1.7, values: {0: OK, 1: Open, 2: Short, 3: Open-Short, 4: CrossTalk, 5: Unknown, 6: Count, 7: NoCable, 8: Other}}
- {name: dlink.CableDiagPair1Length, oid: .1.3.6.1.4.1.171.12.58.1.1.1.9}
- {name: dlink.CableDiagPair2Length, oid: .1.3.6.1.4.1.171.12.58.1.1.1.10}
- {name: dlink.CableDiagPair3Length, oid: .1.3.6.1.4.1.171.12.58.1.1.1.8}
- {name: dlink.CableDiagPair4Length, oid: .1.3.6.1.4.1.171.12.58.1.1.1.11}
- {name: dlink.CableDiagAction, oid: .1.3.6.1.4.1.171.12.58.1.1.1.12, values: {1: Action, 2: Processing, 3: Other}}
- {name: dlink.CableDiagStatus, oid: .1.3.6.1.4.1.171.12.58.1.1.1.13, values: {1: NotRun, 2: Proccessing, 3: LastTestOk, 4: LastTestFailed}}
