############################################## Parameters description  #####################################################
## extra.ge_ports setted only if device response in cableDiag, link isn't correct. GE ports must detect automaticaly      ##
## extra.diag_ports used in cableDiag for diag only cooper ports. Cooper ports not choose automaticaly in diagnostic.
## extra.diag_linkup if setted false, links with operstatus=UP will be ignored, if port are not setted
##
##
############################################################################################################################

models:
 - name: DGS-3000-26TC
   ports: 26
   inputs:
     - snmp
     - telnet
   oids:
     - ./oids/dlink/dgs-3000-26tc.yml
     - ./oids/dlink/common-diag-cable.yml
   detect: {description: ^DGS-3000-26TC Gigabit Ethernet Switch$,  objid: .* }
   extra:
     telnet_conn_type: dlink
     diag_linkup: true
   modules:
     fdb: \SwitcherCore\Modules\Snmp\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Snmp\Link\DlinkParser
     counters: \SwitcherCore\Modules\Snmp\Counters\DefaultParser
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     vlans: \SwitcherCore\Modules\Snmp\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Snmp\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Snmp\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Snmp\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Snmp\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Snmp\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Telnet\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Telnet\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Telnet\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Telnet\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Telnet\Dlink\VlanPortControl
