############################################## Parameters description  #####################################################
## extra.ge_ports setted only if device response in cableDiag, link isn't correct. GE ports must detect automaticaly      ##
## extra.diag_ports used in cableDiag for diag only cooper ports. Cooper ports not choose automaticaly in diagnostic.
## extra.diag_linkup if setted false, links with operstatus=UP will be ignored, if port are not setted
##
##
############################################################################################################################
models:
 - name: D-link DES-3200-10
   ports: 10
   telnet_conn_type: dlink
   oids:
     - ./oids/dlink/des-3200-10-a1.yml
     - ./oids/dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-3200-10,  objid: ^\.1\.3\.6\.1\.4\.1\.171\.10\.113\.1\.1 }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10]
     diag_linkup: true
   modules:
     fdb: \SwitcherCore\Modules\Snmp\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Snmp\Link\DlinkParser
     counters: \SwitcherCore\Modules\Snmp\Counters\DefaultParser
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     vlans: \SwitcherCore\Modules\Snmp\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Snmp\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Snmp\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Snmp\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Snmp\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Snmp\Vlan\VlanByPorts

 - name: D-link DES-3200-10/C1
   ports: 10
   telnet_conn_type: dlink
   oids:
     - ./oids/dlink/des-3200-10-c1.yml
     - ./oids/dlink/des-3200-c1-diag.yml
   detect: {description: ^DES-3200-10\/C1,  objid: ^\.1\.3\.6\.1\.4\.1\.171\.10\.113\.2\.1 }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10]
     diag_linkup: true
   modules:
     fdb: \SwitcherCore\Modules\Snmp\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Snmp\Link\DlinkParser
     counters: \SwitcherCore\Modules\Snmp\Counters\DefaultParser
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     vlans: \SwitcherCore\Modules\Snmp\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Snmp\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Snmp\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Snmp\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Snmp\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Snmp\Vlan\VlanByPorts

 - name: D-link DES-3200-18/C1
   ports: 10
   telnet_conn_type: dlink
   oids:
     - ./oids/dlink/des-3200-18-c1.yml
     - ./oids/dlink/des-3200-c1-diag.yml
   detect: {description: ^DES-3200-18\/C1 Fast Ethernet Switch$,  objid: ^.*113\.3\.1$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
     diag_linkup: true
   modules:
     fdb: \SwitcherCore\Modules\Snmp\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Snmp\Link\DlinkParser
     counters: \SwitcherCore\Modules\Snmp\Counters\DefaultParser
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     vlans: \SwitcherCore\Modules\Snmp\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Snmp\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Snmp\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Snmp\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Snmp\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Snmp\Vlan\VlanByPorts

 - name: D-link DES-3200-26/C1
   ports: 10
   telnet_conn_type: dlink
   oids:
     - ./oids/dlink/des-3200-26-c1.yml
     - ./oids/dlink/des-3200-c1-diag.yml
   detect: {description: ^DES-3200-26\/C1 Fast Ethernet Switch$,  objid: ^.*113\.4\.1$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28]
     diag_linkup: true
     ge_ports: [25,26]
   modules:
     fdb: \SwitcherCore\Modules\Snmp\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Snmp\Link\DlinkParser
     counters: \SwitcherCore\Modules\Snmp\Counters\DefaultParser
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     vlans: \SwitcherCore\Modules\Snmp\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Snmp\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Snmp\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Snmp\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Snmp\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Snmp\Vlan\VlanByPorts

 - name: D-link DES-3200-28/C1
   ports: 10
   telnet_conn_type: dlink
   oids:
     - ./oids/dlink/des-3200-28-c1.yml
     - ./oids/dlink/des-3200-c1-diag.yml
   detect: {description: ^DES-3200-28\/C1 Fast Ethernet Switch$,  objid: ^.*113\.5\.1$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28]
     diag_linkup: true
     ge_ports: [25,26,27,28]
   modules:
     fdb: \SwitcherCore\Modules\Snmp\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Snmp\Link\DlinkParser
     counters: \SwitcherCore\Modules\Snmp\Counters\DefaultParser
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     vlans: \SwitcherCore\Modules\Snmp\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Snmp\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Snmp\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Snmp\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Snmp\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Snmp\Vlan\VlanByPorts

 - name: D-link DES-3200-28F/C1
   ports: 10
   telnet_conn_type: dlink
   oids:
     - ./oids/dlink/des-3200-28F-c1.yml
     - ./oids/dlink/des-3200-c1-diag.yml
   detect: {description: ^DES-3200-28F\/C1 Fast Ethernet Switch$,  objid: ^.*113\.6\.1$ }
   extra:
     diag_ports: [25,26,27,28]
     diag_linkup: true
     ge_ports: [25,26,27,28]
   modules:
     fdb: \SwitcherCore\Modules\Snmp\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Snmp\Link\DlinkParser
     counters: \SwitcherCore\Modules\Snmp\Counters\DefaultParser
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     vlans: \SwitcherCore\Modules\Snmp\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Snmp\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Snmp\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Snmp\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Snmp\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Snmp\Vlan\VlanByPorts

 - name: D-link DES-3200-18
   ports: 18
   telnet_conn_type: dlink
   oids:
     - ./oids/dlink/des-3200-18-a1.yml
     - ./oids/dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-3200-18 Fast Ethernet Switch$,  objid: ^\.1\.3\.6\.1\.4\.1\.171\.10\.113\.1\.2 }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
     diag_linkup: false
   modules:
     fdb: \SwitcherCore\Modules\Snmp\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Snmp\Link\DlinkParser
     counters: \SwitcherCore\Modules\Snmp\Counters\DefaultParser
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     vlans: \SwitcherCore\Modules\Snmp\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Snmp\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Snmp\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Snmp\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Snmp\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Snmp\Vlan\VlanByPorts

 - name: D-link DES-3200-26
   ports: 26
   telnet_conn_type: dlink
   oids:
     - ./oids/dlink/des-3200-26-a1.yml
     - ./oids/dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-3200-26 Fast Ethernet Switch$,  objid: ^.*113.1.5$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]
     diag_linkup: false
   modules:
     fdb: \SwitcherCore\Modules\Snmp\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Snmp\Link\DlinkParser
     counters: \SwitcherCore\Modules\Snmp\Counters\DefaultParser
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     vlans: \SwitcherCore\Modules\Snmp\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Snmp\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Snmp\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Snmp\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Snmp\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Snmp\Vlan\VlanByPorts

 - name: D-link DES-3200-28
   ports: 28
   telnet_conn_type: dlink
   oids:
     - ./oids/dlink/des-3200-28-a1.yml
     - ./oids/dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-3200-28 Fast Ethernet Switch$,  objid: ^.*113.1.3$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,25,26,27,28]
     diag_linkup: false
   modules:
     fdb: \SwitcherCore\Modules\Snmp\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Snmp\Link\DlinkParser
     counters: \SwitcherCore\Modules\Snmp\Counters\DefaultParser
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     vlans: \SwitcherCore\Modules\Snmp\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Snmp\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Snmp\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Snmp\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Snmp\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Snmp\Vlan\VlanByPorts

 - name: D-link DES-3200-28F
   ports: 28
   telnet_conn_type: dlink
   oids:
     - ./oids/dlink/des-3200-28F-a1.yml
     - ./oids/dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-3200-28F Fast Ethernet Switch$,  objid: ^.*113.1.4$ }
   extra:
     diag_ports: [25,26,27,28]
     diag_linkup: false
   modules:
     fdb: \SwitcherCore\Modules\Snmp\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Snmp\Link\DlinkParser
     counters: \SwitcherCore\Modules\Snmp\Counters\DefaultParser
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     vlans: \SwitcherCore\Modules\Snmp\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Snmp\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Snmp\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Snmp\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Snmp\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Snmp\Vlan\VlanByPorts
