############################################## Parameters description  #####################################################
## extra.ge_ports setted only if device response in cableDiag, link isn't correct. GE ports must detect automaticaly      ##
## extra.diag_ports used in cableDiag for diag only cooper ports. Cooper ports not choose automaticaly in diagnostic.
## extra.diag_linkup if setted false, links with operstatus=UP will be ignored, if port are not setted
##
##
############################################################################################################################
models:
 - name: D-link DES-3526
   ports: 26
   oids:
    - ./oids/dlink/des-3526.yml
    - ./oids/dlink/common-diag-cable.yml
   detect: {description: ^DES-3526 Fast-Ethernet Switch$,  objid: 171\.10\.64\.1$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]
     diag_linkup: false
   modules:
     fdb: Snmp\Fdb\DefaultParser
     link: Snmp\Link\DlinkDes3526Parser
    #link: Link\DefaultParser
     counters: Snmp\Counters\DefaultParser
     system: Snmp\System\DefaultParser
     vlan: Snmp\Vlan\DlinkVlanParser
     cable_diag: Snmp\CableDiag\Des3526Parser
     errors: Snmp\Errors\DefaultParser
     rmon: Snmp\Rmon\DefaultParser
     pvid: Snmp\Vlan\PvidParser

 - name: D-link DES-1228/ME
   ports: 28
   oids:
    - ./oids/dlink/des-1228me.yml
    - ./oids/dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-1228\/ME Metro Ethernet Switch$,  objid: 171\.10\.116\.2$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]
     diag_linkup: false
   modules:
     fdb: Snmp\Fdb\DefaultParser
     link: Snmp\Link\DlinkParser
    #link: Link\DefaultParser
     counters: Snmp\Counters\DefaultParser
     system: Snmp\System\DefaultParser
     vlan: Snmp\Vlan\DlinkVlanParser
     cable_diag: Snmp\CableDiag\DlinkParser
     errors: Snmp\Errors\DefaultParser
     rmon: Snmp\Rmon\DefaultParser
     pvid: Snmp\Vlan\PvidParser

 - name: D-link DES-3028
   ports: 28
   telnet_conn_type: dlink
   oids:
     - ./oids/dlink/des-3028.yml
     - ./oids/dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-3028 Fast Ethernet Switch,  objid: .* }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,27,28]
     diag_linkup: false
   modules:
     fdb: Snmp\Fdb\DefaultParser
     link: Snmp\Link\DlinkParser
     #link: Link\DefaultParser
     counters: Snmp\Counters\DefaultParser
     system: Snmp\System\DefaultParser
     vlan: Snmp\Vlan\DlinkVlanParser
     cable_diag: Snmp\CableDiag\DlinkParser
     errors: Snmp\Errors\DefaultParser
     rmon: Snmp\Rmon\DefaultParser
     pvid: Snmp\Vlan\PvidParser
     clear_counters: Telnet\Dlink\ClearCounters
     save_config: Telnet\Dlink\SaveConfig
     reboot: Telnet\Dlink\Reboot


 - name: D-link DES-3028G
   ports: 28
   oids:
     - ./oids/dlink/des-3028G.yml
     - ./oids/dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-3028G Fast Ethernet Switch,  objid: ^.*171\.10\.63\.11$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,27,28]
     diag_linkup: yes
   modules:
     fdb: Snmp\Fdb\DefaultParser
     link: Snmp\Link\DlinkParser
     #link: Link\DefaultParser
     counters: Snmp\Counters\DefaultParser
     system: Snmp\System\DefaultParser
     vlan: Snmp\Vlan\DlinkVlanParser
     cable_diag: Snmp\CableDiag\DlinkParser
     errors: Snmp\Errors\DefaultParser
     rmon: Snmp\Rmon\DefaultParser
     pvid: Snmp\Vlan\PvidParser

 - name: Dlink DGS-1100-06/ME/A1
   ports: 6
   oids:
     - ./oids/dlink/dgs-1100-06-me-a1.yml
   detect: {description: ^DGS-1100-06\/ME\/A1$,  objid: ^.*.171.10.134.1$ }
   extra:
     diag_ports: [1,2,3,4,5]
     diag_linkup: false
     ge_ports: [1,2,3,4,5,6]
   modules:
     fdb: Snmp\Fdb\DefaultParser
     link: Snmp\Link\DlinkDgs1100Parser
     counters: Snmp\Counters\DefaultParser
     system: Snmp\System\DefaultParser
     cable_diag: Snmp\CableDiag\DlinkDgs1100Parser
     vlan: Snmp\Vlan\DlinkVlanParser
     errors: Snmp\Errors\DefaultParser
     rmon: Snmp\Rmon\DefaultParser
     pvid: Snmp\Vlan\PvidParser

 - name: Dlink DGS-1100-10/ME
   ports: 10
   oids:
     - ./oids/dlink/dgs-1100-10-me.yml
   detect: {description: ^DGS-1100-10\/ME,  objid: ^.*.171.10.134.2.1$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10]
     diag_linkup: false
     ge_ports: [1,2,3,4,5,6,7,8,9,10]
   modules:
     fdb: Snmp\Fdb\DefaultParser
     link: Snmp\Link\DlinkDgs1100Parser
     counters: Snmp\Counters\DefaultParser
     system: Snmp\System\DefaultParser
     cable_diag: Snmp\CableDiag\DlinkDgs1100Parser
     vlan: Snmp\Vlan\DlinkVlanParser
     errors: Snmp\Errors\DefaultParser
     rmon: Snmp\Rmon\DefaultParser
     pvid: Snmp\Vlan\PvidParser