############################################## Parameters description  #####################################################
##
############################################################################################################################

models:
 - name: Mikrotik RB1100AHx2
   ports: 0
   detect: {description: ^RouterOS RB1100AHx2$,  objid: ^.1.3.6.1.4.1.14988.1$ }
   inputs:
     - snmp
     - routeros_api
   modules:
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     arp_info: \SwitcherCore\Modules\RouterOS\ArpInfo
     arp_ping: \SwitcherCore\Modules\RouterOS\ArpPing
     interface_vlan_info: \SwitcherCore\Modules\RouterOS\InterfaceVlanInfo

 - name: Mikrotik CCR1009-7G-1C-1S+
   ports: 0
   detect: {description: ^RouterOS CCR1009-7G-1C-1S\+$,  objid: ^.1.3.6.1.4.1.14988.1$ }
   inputs:
     - snmp
     - routeros_api
   modules:
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     arp_info: \SwitcherCore\Modules\RouterOS\ArpInfo
     arp_ping: \SwitcherCore\Modules\RouterOS\ArpPing
     interface_vlan_info: \SwitcherCore\Modules\RouterOS\InterfaceVlanInfo

 - name: Mikrotik RB952Ui-5ac2nD
   ports: 0
   detect: {description: ^RouterOS RB952Ui-5ac2nD$,  objid: ^.1.3.6.1.4.1.14988.1$ }
   inputs:
     - snmp
     - routeros_api
   modules:
     system: \SwitcherCore\Modules\Snmp\System\DefaultParser
     arp_info: \SwitcherCore\Modules\RouterOS\ArpInfo
     arp_ping: \SwitcherCore\Modules\RouterOS\ArpPing
     interface_vlan_info: \SwitcherCore\Modules\RouterOS\InterfaceVlanInfo
     dhcp_server_info: \SwitcherCore\Modules\RouterOS\DhcpServerInfo
     lease_info: \SwitcherCore\Modules\RouterOS\LeaseInfo
     ctrl_static_arp: \SwitcherCore\Modules\RouterOS\StaticArpControl
     ctrl_static_lease: \SwitcherCore\Modules\RouterOS\StaticLeaseControl
