############################################## Parameters description  #####################################################
## extra.ge_ports setted only if device response in cableDiag, link isn't correct. GE ports must detect automaticaly      ##
## extra.diag_ports used in cableDiag for diag only cooper ports. Cooper ports not choose automaticaly in diagnostic.
## extra.diag_linkup if setted false, links with operstatus=UP will be ignored, if port are not setted
##
##
############################################################################################################################
models:
 - name: D-link DES-3526
   ports: 26
   oids:
    - ./dlink/des-3526.yml
    - ./dlink/common-diag-cable.yml
   detect: {description: ^DES-3526 Fast-Ethernet Switch$, hardware: .*, objid: 171\.10\.64\.1$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]
     diag_linkup: false
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkDes3526Parser
    #link: Link\DefaultParser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     cable_diag: CableDiag\Des3526Parser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: D-link DES-1228/ME
   ports: 28
   oids:
    - ./dlink/des-1228me.yml
    - ./dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-1228\/ME Metro Ethernet Switch$, hardware: .*, objid: 171\.10\.116\.2$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]
     diag_linkup: false
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkParser
    #link: Link\DefaultParser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     cable_diag: CableDiag\DlinkParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: D-link DES-3028
   ports: 28
   oids:
     - ./dlink/des-3028.yml
     - ./dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-3028 Fast Ethernet Switch, hardware: .*, objid: .* }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,27,28]
     diag_linkup: false
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkParser
     #link: Link\DefaultParser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     cable_diag: CableDiag\DlinkParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: D-link DES-3028G
   ports: 28
   oids:
     - ./dlink/des-3028G.yml
     - ./dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-3028G Fast Ethernet Switch, hardware: .*, objid: ^.*171\.10\.63\.11$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,27,28]
     diag_linkup: yes
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkParser
     #link: Link\DefaultParser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     cable_diag: CableDiag\DlinkParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: D-link DES-3200-10
   ports: 10
   oids:
     - ./dlink/des-3200-10-a1.yml
     - ./dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-3200-10, hardware: .*, objid: ^\.1\.3\.6\.1\.4\.1\.171\.10\.113\.1\.1 }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10]
     diag_linkup: true
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkParser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     cable_diag: CableDiag\DlinkParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: D-link DES-3200-10/C1
   ports: 10
   oids:
     - ./dlink/des-3200-10-c1.yml
     - ./dlink/des-3200-c1-diag.yml
   detect: {description: ^DES-3200-10\/C1, hardware: .*, objid: ^\.1\.3\.6\.1\.4\.1\.171\.10\.113\.2\.1 }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10]
     diag_linkup: true
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkParser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     cable_diag: CableDiag\DlinkParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: D-link DES-3200-18/C1
   ports: 10
   oids:
     - ./dlink/des-3200-18-c1.yml
     - ./dlink/des-3200-c1-diag.yml
   detect: {description: ^DES-3200-18\/C1 Fast Ethernet Switch$, hardware: .*, objid: ^.*113\.3\.1$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
     diag_linkup: true
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkParser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     cable_diag: CableDiag\DlinkParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: D-link DES-3200-26/C1
   ports: 10
   oids:
     - ./dlink/des-3200-26-c1.yml
     - ./dlink/des-3200-c1-diag.yml
   detect: {description: ^DES-3200-26\/C1 Fast Ethernet Switch$, hardware: .*, objid: ^.*113\.4\.1$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28]
     diag_linkup: true
     ge_ports: [25,26]
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkParser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     cable_diag: CableDiag\DlinkParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: D-link DES-3200-28/C1
   ports: 10
   oids:
     - ./dlink/des-3200-28-c1.yml
     - ./dlink/des-3200-c1-diag.yml
   detect: {description: ^DES-3200-28\/C1 Fast Ethernet Switch$, hardware: .*, objid: ^.*113\.5\.1$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28]
     diag_linkup: true
     ge_ports: [25,26,27,28]
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkParser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     cable_diag: CableDiag\DlinkParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: D-link DES-3200-28F/C1
   ports: 10
   oids:
     - ./dlink/des-3200-28F-c1.yml
     - ./dlink/des-3200-c1-diag.yml
   detect: {description: ^DES-3200-28F\/C1 Fast Ethernet Switch$, hardware: .*, objid: ^.*113\.6\.1$ }
   extra:
     diag_ports: [25,26,27,28]
     diag_linkup: true
     ge_ports: [25,26,27,28]
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkParser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     cable_diag: CableDiag\DlinkParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: D-link DES-3200-18
   ports: 18
   oids:
     - ./dlink/des-3200-18-a1.yml
     - ./dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-3200-18 Fast Ethernet Switch$, hardware: .*, objid: ^\.1\.3\.6\.1\.4\.1\.171\.10\.113\.1\.2 }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
     diag_linkup: false
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkParser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     cable_diag: CableDiag\DlinkParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: D-link DES-3200-26
   ports: 26
   oids:
     - ./dlink/des-3200-26-a1.yml
     - ./dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-3200-26 Fast Ethernet Switch$, hardware: .*, objid: ^.*113.1.5$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]
     diag_linkup: false
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkParser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     cable_diag: CableDiag\DlinkParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: D-link DES-3200-28
   ports: 28
   oids:
     - ./dlink/des-3200-28-a1.yml
     - ./dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-3200-28 Fast Ethernet Switch$, hardware: .*, objid: ^.*113.1.3$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,25,26,27,28]
     diag_linkup: false
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkParser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     cable_diag: CableDiag\DlinkParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: D-link DES-3200-28F
   ports: 28
   oids:
     - ./dlink/des-3200-28F-a1.yml
     - ./dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-3200-28F Fast Ethernet Switch$, hardware: .*, objid: ^.*113.1.4$ }
   extra:
     diag_ports: [25,26,27,28]
     diag_linkup: false
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkParser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     cable_diag: CableDiag\DlinkParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: Dlink DGS-1210-28/ME/A2
   ports: 28
   oids:
     - ./dlink/dgs-1210-28-me-a2.yml
   detect: {description: ^DGS-1210-28\/ME\/A2$, hardware: .*, objid: ^.*171.10.76.28.1$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
     diag_linkup: true
     ge_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28]
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkDgs1210Parser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     cable_diag: CableDiag\DlinkParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: Dlink DGS-1210-20/ME/A1
   ports: 20
   oids:
     - ./dlink/dgs-1210-20-me-a1.yml
   detect: {description: ^DGS-1210-20\/ME\/A1$, hardware: .*, objid: ^.*171\.10\.76\.31\.1$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
     diag_linkup: true
     ge_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkDgs1210Parser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     cable_diag: CableDiag\DlinkParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: Dlink DGS-1210-10/ME/A1
   ports: 10
   oids:
     - ./dlink/dgs-1210-10-me-a1.yml
   detect: {description: ^DGS-1210-10\/ME\/A1$, hardware: .*, objid: ^.*171.10.76.35.1$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8]
     diag_linkup: true
     ge_ports: [1,2,3,4,5,6,7,8,9,10]
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkDgs1210Parser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     cable_diag: CableDiag\DlinkParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: Dlink DGS-1210-20/ME/B1
   ports: 20
   oids:
     - ./dlink/dgs-1210-20-me-b1.yml
   detect: {description: ^DGS-1210-20\/ME\/B1$, hardware: .*, objid: ^.*171.10.76.31.2$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
     diag_linkup: true
     ge_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkDgs1210Parser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     cable_diag: CableDiag\DlinkParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: Dlink DGS-1210-28/ME/B1
   ports: 28
   oids:
     - ./dlink/dgs-1210-28-me-b1.yml
   detect: {description: ^DGS-1210-28\/ME\/B1$, hardware: .*, objid: ^.*171.10.76.28.2$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
     diag_linkup: true
     ge_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28]
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkDgs1210Parser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     cable_diag: CableDiag\DlinkParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: Dlink DGS-1210-28XS/ME/B1
   ports: 28
   oids:
     - ./dlink/dgs-1210-28xs-me-b1.yml
   detect: {description: ^DGS-1210-28XS\/ME\/B1$, hardware: .*, objid: ^.*171.10.76.39.1$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28]
     diag_linkup: true
     ge_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28]
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkDgs1210Parser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     vlan: Vlan\DlinkVlanParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser

 - name: Dlink DGS-1100-06/ME/A1
   ports: 06
   oids:
     - ./dlink/dgs-1100-06-me-a1.yml
   detect: {description: ^DGS-1100-06\/ME\/A1$, hardware: .*, objid: ^.*.171.10.134.1$ }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28]
     diag_linkup: true
     ge_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28]
   parsers:
     fdb: Fdb\DefaultParser
     link: Link\DlinkDgs1100Parser
     counters: Counters\DefaultParser
     system: System\DefaultParser
     cable_diag: CableDiag\DlinkParser
     vlan: Vlan\DlinkVlanParser
     errors: Errors\DefaultParser
     rmon: Rmon\DefaultParser
     pvid: Vlan\PvidParser