models:
 - name: D-link DES-3028
   ports: 28
   oids:
     - ./dlink/des-3028.yml
   detect: {description: ^D-Link DES-3028$, hardware: .*, objid: .* }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,27,28]
     combo_ports: [25, 26]
 - name: D-link DES-2026
   ports: 28
   oids:
     - ./dlink/des-3028.yml
   detect: {description: ^D-Link DES-3028$, hardware: .*, objid: .* }
   extra:
     diag_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,27,28]
     combo_ports: [25, 26]