#Module for get system info + meta
- name: system

#Module for get link info
- name: link_info
  arguments:
    - {name: port, pattern: '^[0-9]{1,3}$', required: no}

#Module for get counters
- name: counters
  arguments:
    - {name: port, pattern: '^[0-9]{1,3}$', required: no}

#Module for get errors
- name: errors
  arguments:
    - {name: port, pattern: '^[0-9]{1,3}$', required: no}

#Module for get rmon data
- name: rmon
  arguments:
    - {name: port, pattern: '^[0-9]{1,3}$', required: no}

#Module for get FDB
- name: fdb
  arguments:
    - {name: port, pattern: '^[0-9]{1,3}$', required: no}
    - {name: mac, pattern: '^[a-fA-F0-9:]{17}|[a-fA-F0-9]{12}$', required: no}
    - {name: vlan_id, pattern: '^[0-9]{1,4}$', required: no}

#Get vlan info from device
- name: vlans
  arguments:
    - {name: vlan_id, pattern: '^[0-9]{1,4}$', required: no}

#Get vlan info from device by ports
- name: vlans_by_port
  arguments:
    - {name: port, pattern: '^[0-9]{1,3}$', required: no}
  depends:
    - vlans

- name: pvid
  arguments:
    - {name: port, pattern: '^[0-9]{1,3}$', required: no}

#Cable diagnostic module
- name: cable_diag
  arguments:
    - {name: port, pattern: '^[0-9]{1,3}$', required: no}

#Action clear counters
- name: clear_counters

#Action save configuration
- name: save_config

#Action reboot
- name: reboot

#Action port state control
- name: ctrl_port_state
  arguments:
    - {name: port, pattern: '^[0-9]{1,4}$', required: yes}
    - {name: state, pattern: '^(disable|enable)$', required: yes, values: [disable, enable]}

#Action port state speed
- name: ctrl_port_speed
  arguments:
    - {name: port, pattern: '^[0-9]{1,4}$', required: yes}
    - {name: speed, pattern: '^auto|(10|100|1000|10000)-(Half|Full)$', required: yes, values: [auto, 10-Full, 100-Full, 1000-Full]}

#Action port state desciption
- name: ctrl_port_descr
  arguments:
    - {name: port, pattern: '^[0-9]{1,4}$', required: yes}
    - {name: description, pattern: '^[0-9a-zA-Z_]{1,}$', required: yes}

#Action for vlan state control
- name: ctrl_vlan_state
  arguments:
    - {name: id, pattern: '^[0-9]{1,4}$', required: no}
    - {name: name, pattern: '^[0-9a-zA-Z_]{1,16}$', required: no}
    - {name: action, pattern: '^(delete|create)$', required: yes, values: [delete, create]}

#Action for vlan state control
- name: ctrl_vlan_port
  arguments:
    - {name: id, pattern: '^[0-9]{1,4}$', required: yes}
    - {name: port, pattern: '^[0-9]{1,4}$', required: yes}
    - {name: type, pattern: '^(tagged|untagged)$', required: no, values: [tagged, untagged]}
    - {name: action, pattern: '^(delete|add)$', required: yes, values: [delete, add]}

#Action Get arp info with filters
- name: arp_info
  arguments:
    - {name: ip, pattern: '^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$', required: no}
    - {name: vlan_id, pattern: '^[0-9]{1,4}$', required: no}
    - {name: mac, pattern: '^[a-fA-F0-9:]{17}|[a-fA-F0-9]{12}$', required: no}
  depends:
    - interface_vlan_info

#Action Get arp info with filters
- name: interface_vlan_info
  arguments:
    - {name: name, pattern: '^[0-9a-zA-Z_]{1,16}$', required: no}
    - {name: vlan_id, pattern: '^[0-9]{1,4}$', required: no}

#Action Get arp info with filters
- name: arp_ping
  arguments:
    - {name: ip, pattern: '^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$', required: yes}
    - {name: vlan_id, pattern: '^[0-9]{1,4}$', required: no}
    - {name: vlan_name, pattern: '^[0-9a-zA-Z_\-]{1,}$', required: no}
    - {name: count, pattern: '^[0-9]{1,}$', required: no}
  depends:
    - interface_vlan_info