commands:
- name: reboot
  lines:
  - { line: 'reboot', wait_for: '#', fail: '.*' }
  - { line: 'Y', wait_for: '#', fail: '.*' }
  ignore_fail: yes
- name: create_vlan
  lines:
  - { line: 'create vlan {{vlan_id}}', wait_for: '#', fail: '.*' }
  ignore_fail: yes
